# Generated by Django 4.0.4 on 2022-09-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
